### ISSUE TITLE
Перепроверьте правила.

### ISSUE THREAD

**Issue by JjGjGq** [SocolSRT/cloudflare-rules#1]
Здравствуйте.
Есть дубли, есть несуществующие ASN https://ipinfo.io/AS477764

Сейчас много кто использует ВПН, ваши правила не совсем ли жесткие? Блокировать DO провайдера например и еще ряд популярных...

**Comment by SocolSRT** [comment]
Здравствуйте, было найдено и удалено 3 дубля, все ASN существуют (477764 отсутствует в списке).
Много атак происходят с Tor/VPN/Proxy сетей, если человеку нужен трафик с этих сетей, он может удалить данное ограничение в один клик. (и о каких популярных провайдеров идёт речь?, если у провайдера не распознаётся страна, его уже нельзя считать популярным)

**Comment by JjGjGq** [comment]
А как же это вот https://prnt.sc/H3w9HbBkCA_e ?

сб, 18 июн. 2022 г. в 11:07, Socol ***@***.***>:

**Comment by SocolSRT** [comment]
Вы про это правило, уточнили бы сразу, убрал 477764
Там специально продублировано под разные условия.

**Comment by JjGjGq** [comment]
Это блокируется яндекс бот https://prnt.sc/PF4tvgqFGAW6 ?

сб, 18 июн. 2022 г. в 16:18, Socol ***@***.***>:

**Comment by JjGjGq** [comment]
https://prnt.sc/2d4VyDklQkrY
Service | Access rules: ASN

вс, 19 июн. 2022 г. в 02:55, Hjj Jjj ***@***.***>:

**Comment by SocolSRT** [comment]
Service | Access rules: ASN - ни как не связан с моими правилами, вы сами заблокировали сеть яндекс.
Так же, я не являюсь агентом поддержки cloudflare, поэтому обращайтесь к ним с такими вопросами.
Если возникнут вопросы по платным услугам safeness.su, можете обратиться в группу VK (vk.com/safeness_su) или на почту contact@safeness.su, там я вам отвечу.

**Comment by JjGjGq** [comment]
>> Так же, я не являюсь агентом поддержки cloudflare
Зачем тогда создали https://github.com/SocolSRT/cloudflare-rules ? Вопросы
сугубо по теме.

Правила установил 1в1 только с вашей темы, только они могли заблокировать
не то. Я не мог заблокировать яндекс, так как до правил он ходил без
проблем.

Вы вообще используете эти правила в своих проектах или просто так для людей
написали?


вс, 19 июн. 2022 г. в 12:14, Socol ***@***.***>:

**Comment by SocolSRT** [comment]
Для тех кому нужен шаблон правил, от которых они могут отталкиваться и подстраивать под свои сайты. (я не собираюсь для каждого лично настраивать правила)

Не знаю, что вы сделали, но там была блокировка не от правил. (Блокировка от правил выглядит так - Service: Firewall rules)

На некоторых подпроектах ещё используется (и подобных проблем, не наблюдается), но я по немного переношу их на свою защиту, она показывает более хорошую фильтрацию.
